# -*- coding: utf-8 -*-
"""TPI_Glassdoor_Entrega2 Toscanini - Villarrubia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18UxSLQre4GNflxUuRXsgcXxs1-YnxXfs

# Trabajo Práctico Integrador — Introducción al Análisis de Datos
Materia: Introducción al Análisis de Datos  
Segunda Entrega
Alumnos: Toscanini Juan Manuel - Villarrubia Roberto
---

### Observación 1
El dataset no presenta valores nulos reales. En su lugar utiliza el valor -1
como código para datos desconocidos, tanto en columnas numéricas (Rating, Founded)
como en columnas de texto (Competitors, Industry.).
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import io

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 5)

import warnings
warnings.filterwarnings('ignore')
import kagglehub


path = kagglehub.dataset_download("rashikrahmanpritom/data-science-job-posting-on-glassdoor")

##
print("Path to dataset files:", path)
path = "/kaggle/input/data-science-job-posting-on-glassdoor"
df = pd.read_csv(path + "/Uncleaned_DS_jobs.csv")

print(f"Dataset cargado correctamente ✓")
print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")


df.head()
df.tail()
df.shape
df.dtypes
df.info()
df.describe()
duplicados = df.duplicated().sum()
print(f"Registros duplicados: {duplicados}")

"""### Observación 2
El dataset no presenta registros duplicados. Las 672 filas son ofertas laborales únicas.
"""

duplicados = df.duplicated().sum()
print(f"Registros duplicados: {duplicados}")

"""### Observación 3
Varias columnas usan '-1' como dato faltante. La columna Competitors es la más
afectada con 501 valores faltantes (74% del dataset), lo que la hace poco útil
para el análisis. Industry y Sector tienen 71 valores faltantes cada una, y
Size, Type of ownership y Revenue tienen 27 cada una.
"""

print("Valores -1 en columnas de texto:")
for col in df.select_dtypes(include='object').columns:
    count = (df[col] == '-1').sum()
    if count > 0:
        print(f"  {col}: {count} valores")

"""### Observación 4
En columnas numéricas también aparece el -1 como dato faltante: Rating tiene
50 valores (-1) y Founded tiene 118.

"""

print("Valores -1 en columnas numéricas:")
for col in df.select_dtypes(include='number').columns:
    count = (df[col] == -1).sum()
    if count > 0:
        print(f"  {col}: {count} valores")

"""### Observación 5
Filtrando los valores -1, el Rating válido de 622 empresas muestra una media de
3.88 sobre 5, con la mayoría de las empresas concentradas entre 3.5 y 4.4.
No hay empresas con rating menor a 2.0, lo que sugiere que las empresas con
muy mala reputación publican pocas ofertas en Glassdoor.
"""

rating_valido = df[df['Rating'] > 0]['Rating']
print(rating_valido.describe().round(2))

"""## 1.2 — Visualizaciones"""

fig, ax = plt.subplots()
sns.histplot(rating_valido, bins=20, kde=True, color='steelblue', ax=ax)
ax.axvline(rating_valido.mean(), color='red', linestyle='--', label=f'Media: {rating_valido.mean():.2f}')
ax.set_title('Distribución del Rating de las empresas')
ax.set_xlabel('Rating')
ax.set_ylabel('Cantidad de ofertas')
ax.legend()
plt.show()

"""**Gráfico 1 — Distribución del Rating:** La mayoría de las empresas se concentran
entre 3.5 y 4.0. No hay empresas con rating menor a 2.0, lo que indica que las
compañías con peor reputación publican pocas ofertas en Glassdoor.
"""

top_sectores = df[df['Sector'] != '-1']['Sector'].value_counts().head(10)

fig, ax = plt.subplots()
top_sectores.plot(kind='barh', ax=ax, color='steelblue')
ax.set_title('Top 10 sectores con más ofertas de Data Science')
ax.set_xlabel('Cantidad de ofertas')
ax.set_ylabel('Sector')
plt.tight_layout()
plt.show()

"""**Gráfico 2 — Sectores con más ofertas:** Information Technology concentra la mayor
demanda de perfiles Data Science, seguido por Business Services y Biotech &
Pharmaceuticals. Esto muestra que el análisis de datos no es exclusivo del sector
tech: salud e industria farmacéutica también tienen alta demanda.
"""

top_titles = df['Job Title'].value_counts().head(10)

fig, ax = plt.subplots()
top_titles.plot(kind='barh', ax=ax, color='steelblue')
ax.set_title('Top 10 títulos de puestos más publicados')
ax.set_xlabel('Cantidad de ofertas')
ax.set_ylabel('Título')
plt.tight_layout()
plt.show()

"""**Gráfico 3 — Títulos más publicados:** "Data Scientist" es el puesto más demandado
por lejos, seguido por "Data Engineer" y "Senior Data Scientist". La gran variedad
de títulos muestra falta de estandarización en el área: un mismo perfil puede
aparecer con nombres distintos según la empresa.
"""

size_order = [
    '1 to 50 employees',
    '51 to 200 employees',
    '201 to 500 employees',
    '501 to 1000 employees',
    '1001 to 5000 employees',
    '5001 to 10000 employees',
    '10000+ employees'
]

size_data = df[df['Size'] != '-1']['Size'].value_counts()
size_data = size_data.reindex([s for s in size_order if s in size_data.index])

fig, ax = plt.subplots()
size_data.plot(kind='bar', ax=ax, color='steelblue')
ax.set_title('Distribución de ofertas por tamaño de empresa')
ax.set_xlabel('Tamaño')
ax.set_ylabel('Cantidad de ofertas')
ax.set_xticklabels(ax.get_xticklabels(), rotation=30, ha='right')
plt.tight_layout()
plt.show()

"""**Gráfico 4 — Tamaño de empresa:** Las empresas medianas (51 a 200 empleados)
concentran la mayor cantidad de ofertas, seguidas por las de 1001 a 5000 empleados.
La distribución es bastante pareja entre categorías, lo que indica que los perfiles
de Data Science tienen demanda en empresas de todos los tamaños.

## 1.3 — Preguntas analíticas

A partir del análisis exploratorio surgen las siguientes hipótesis que
orientarán el trabajo en las secciones siguientes:

1. ¿Qué sector ofrece los salarios más altos para perfiles de Data Science?

2. ¿Qué título de puesto tiene el salario promedio más alto?

# Sección 2 - Preparacion de datos
### 2.1 — Variable objetivo para el modelo supervisado

El dataset no presenta una variable objetivo numérica directa.
La columna `Salary Estimate` contiene rangos salariales en formato texto
(por ejemplo, `"$80K-$100K (Glassdoor est.)"`), por lo que se construirá
una nueva variable `avg_salary` calculando el promedio entre el límite
inferior y superior de cada rango, expresado en miles de dólares anuales.

Esta variable será el objetivo del modelo supervisado, planteando un
problema de **regresión**: predecir el salario promedio estimado de una
oferta de Data Science a partir de características como el sector,
el tamaño de la empresa, la ubicación y el rating.

La elección está justificada porque el salario es la variable de mayor
interés práctico en un dataset de ofertas laborales, y la información
necesaria para construirla está presente en todas las filas del dataset.
"""

import kagglehub
import pandas as pd

path = kagglehub.dataset_download("rashikrahmanpritom/data-science-job-posting-on-glassdoor")
df = pd.read_csv(path + "/Uncleaned_DS_jobs.csv")
print(f"Dataset cargado ✓ — {df.shape[0]} filas, {df.shape[1]} columnas")

# Construir variable objetivo: salario promedio estimado (en USD)
def extraer_salario_promedio(texto):
    import re
    numeros = re.findall(r'\$(\d+)K', texto)
    if len(numeros) == 2:
        return (int(numeros[0]) + int(numeros[1])) / 2
    return None

df['avg_salary'] = df['Salary Estimate'].apply(extraer_salario_promedio)

print(f"Valores generados: {df['avg_salary'].notna().sum()} de {len(df)}")
print(df['avg_salary'].describe().round(2))

"""### 2.2 — Selección de variables

**Modelo supervisado (regresión):**
Se utilizarán las siguientes variables para predecir `avg_salary`:
- `Rating`: valoración de la empresa (numérica, requiere tratar -1)
- `Size`: tamaño de la empresa (categórica)
- `Type of ownership`: tipo de organización (categórica)
- `Industry`: industria del puesto (categórica)
- `Sector`: sector económico (categórica)
- `seniority`: nivel de seniority extraído del título (se construirá en 2.4)
- `python_yn`, `spark_yn`, `aws_yn`, `excel_yn`: habilidades técnicas mencionadas en la descripción (se construirán en 2.4)

Se excluyen columnas como `Job Title`, `Job Description`, `Company Name`
y `Competitors` por ser texto libre o tener demasiados valores faltantes,
y `Salary Estimate` por ser la fuente de la variable objetivo.

**Modelo no supervisado (clustering):**
Se utilizarán `avg_salary`, `Rating`, `Size` y `Sector` para segmentar
perfiles de ofertas laborales. Se busca identificar grupos con características
similares en términos de compensación, reputación empresarial y contexto organizacional.
"""

# Variables seleccionadas para modelo supervisado
features_supervisado = ['Rating', 'Size', 'Type of ownership', 'Industry', 'Sector']

# Variables seleccionadas para modelo no supervisado
features_no_supervisado = ['avg_salary', 'Rating', 'Size', 'Sector']

print("Variables supervisado:", features_supervisado)
print("Variables no supervisado:", features_no_supervisado)
print("\nVista previa:")
df[features_supervisado + ['avg_salary']].head()

"""### 2.3 — Tratamiento de problemas de calidad

Abordamos los problemas detectados en la Sección 1:

- **Valores -1 en `Rating`**: se reemplazan por NaN y luego por la media
  de los ratings válidos, ya que solo afectan al 7% de los datos y la
  distribución es aproximadamente normal.
- **Valores -1 en columnas categóricas**: se reemplazan por NaN y luego
  por la moda de cada columna, excepto `Competitors` que se elimina
  directamente por tener 74% de valores faltantes.
- **Duplicados**: no se encontraron en la Sección 1, se confirma aquí.
- **Outliers en `avg_salary`**: se verifica la distribución; valores
  extremos se conservan por ser plausibles en el mercado laboral de Data Science.
"""

import numpy as np
import pandas as pd

df_clean = df.copy()

# Eliminar columna con 74% de faltantes
df_clean.drop(columns=['Competitors'], inplace=True)

# Reemplazar -1 por NaN en Rating y Founded
df_clean['Rating'] = df_clean['Rating'].replace(-1, np.nan)
df_clean['Founded'] = df_clean['Founded'].replace(-1, np.nan)

# Imputar Rating con la media
media_rating = df_clean['Rating'].mean()
df_clean['Rating'] = df_clean['Rating'].fillna(media_rating)
print(f"Rating imputado con media: {media_rating:.2f}")

# Reemplazar '-1' por NaN en columnas categóricas y imputar con moda
cols_cat = ['Size', 'Type of ownership', 'Industry', 'Sector']
for col in cols_cat:
    df_clean[col] = df_clean[col].replace('-1', np.nan)
    moda = df_clean[col].mode()[0]
    df_clean[col] = df_clean[col].fillna(moda)
    print(f"{col}: imputado con moda '{moda}'")

print(f"\nNulos restantes en columnas clave:")
print(df_clean[['Rating', 'Size', 'Type of ownership', 'Industry', 'Sector']].isnull().sum())

print(f"\nDuplicados: {df_clean.duplicated().sum()}")

"""### 2.4 — Transformaciones

Aplicamos las siguientes transformaciones:

- **Variables de habilidades técnicas**: se crean columnas binarias (0/1)
  a partir de `Job Description`, detectando menciones en Pyhton
- **Seniority**: se extrae del `Job Title` una variable ordinal con tres niveles
  (junior, senior, lead/manager) para capturar el nivel jerárquico del puesto.
- **Codificación ordinal de `Size`**: el tamaño de empresa tiene un orden natural
  (de menor a mayor), por lo que se codifica de forma ordinal en lugar de one-hot.
- **One-hot encoding**: se aplica a `Type of ownership`, `Industry` y `Sector`,
  ya que son categóricas sin orden inherente.
- **Eliminación de columnas irrelevantes**: se descartan columnas de texto libre
  o que no aportan al modelado (`Job Title`, `Job Description`, `Company Name`,
  `Location`, `Headquarters`, `Salary Estimate`, `Founded`).
- **Escalado**: se aplicará en la sección de modelado según el algoritmo elegido.

"""

# Variables de habilidades técnicas
df_clean['python_yn'] = df_clean['Job Description'].str.lower().str.contains('python').astype(int)
df_clean['spark_yn']  = df_clean['Job Description'].str.lower().str.contains('spark').astype(int)
df_clean['aws_yn']    = df_clean['Job Description'].str.lower().str.contains('aws').astype(int)
df_clean['excel_yn']  = df_clean['Job Description'].str.lower().str.contains('excel').astype(int)

print("Habilidades técnicas detectadas:")
print(df_clean[['python_yn','spark_yn','aws_yn','excel_yn']].sum())

# Seniority desde Job Title
def extraer_seniority(titulo):
    titulo = titulo.lower()
    if any(x in titulo for x in ['manager', 'director', 'lead', 'head', 'vp', 'principal']):
        return 'senior'
    elif any(x in titulo for x in ['senior', 'sr.', 'sr ']):
        return 'senior'
    elif any(x in titulo for x in ['junior', 'jr.', 'jr ', 'entry']):
        return 'junior'
    else:
        return 'mid'

df_clean['seniority'] = df_clean['Job Title'].apply(extraer_seniority)
print("\nDistribución seniority:")
print(df_clean['seniority'].value_counts())

# Codificación ordinal de Size
size_order = {
    '1 to 50 employees': 1,
    '51 to 200 employees': 2,
    '201 to 500 employees': 3,
    '501 to 1000 employees': 4,
    '1001 to 5000 employees': 5,
    '5001 to 10000 employees': 6,
    '10000+ employees': 7
}
df_clean['size_encoded'] = df_clean['Size'].map(size_order)

# Hay filas con Size = 'Unknown' que no están en size_order, quedan como NaN
# completamos con la mediana para no perder esas filas
if df_clean['size_encoded'].isna().any():
    n_unknown = df_clean['size_encoded'].isna().sum()
    mediana_size = df_clean['size_encoded'].median()
    df_clean['size_encoded'] = df_clean['size_encoded'].fillna(mediana_size)
    print(f"size_encoded: {n_unknown} filas con Size desconocido, imputadas con mediana ({mediana_size})")

#
df_model = pd.get_dummies(df_clean, columns=['Type of ownership', 'Industry', 'Sector', 'seniority'], drop_first=True)

# para eliminar columnas innecesarias
cols_eliminar = ['Job Title', 'Job Description', 'Company Name',
                 'Location', 'Headquarters', 'Salary Estimate', 'Founded', 'Size',
                 'Revenue', 'index']
cols_eliminar = [c for c in cols_eliminar if c in df_model.columns]
df_model.drop(columns=cols_eliminar, inplace=True)

# sacamos filas donde avg_salary quedó en NaN (salarios por hora, valores -1)

filas_antes = df_model.shape[0]
df_model = df_model.dropna(subset=['avg_salary']).reset_index(drop=True)
filas_despues = df_model.shape[0]
print(f"Filas eliminadas por avg_salary nulo: {filas_antes - filas_despues}")

print(f"\nDimensiones finales del dataset para modelado: {df_model.shape}")
print(df_model.head(2))

"""### 2.5 — Dataset final y partición train/test

Se generan dos versiones finales del dataset:
- `df_model`: dataset completo con todas las transformaciones, para uso en modelado supervisado y no supervisado.
- Split 80/20 entre entrenamiento y prueba para el modelo supervisado,
  con `random_state=42` para reproducibilidad.

Se usa estratificación por `seniority_mid` para mantener proporciones
similares entre ambos conjuntos dado el desbalance observado (85% mid-level).
"""

from sklearn.model_selection import train_test_split

# Separar variable objetivo y predictoras
X = df_model.drop(columns=['avg_salary'])
y = df_model['avg_salary']

# Partición 80/20
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Dataset completo:     {df_model.shape}")
print(f"X_train: {X_train.shape}  |  y_train: {y_train.shape}")
print(f"X_test:  {X_test.shape}   |  y_test:  {y_test.shape}")

# Guarda version final
df_no_supervisado = df_model[['avg_salary', 'Rating', 'size_encoded'] +
                              [c for c in df_model.columns if c.startswith('Sector_')]].copy()

print(f"\nDataset no supervisado: {df_no_supervisado.shape}")

"""### 2.6 — Conclusiones de la preparación de datos

El dataset esta listo para el modelado en dos versiones:

- **Supervisado**: 537 muestras de entrenamiento y 135 de prueba, con 96 variables
  predictoras que incluyen características de la empresa, habilidades técnicas requeridas
  y nivel de seniority del puesto.
- **No supervisado**: 672 filas con 24 variables centradas en salario, rating,
  tamaño de empresa y sector para identificar perfiles de ofertas laborales.

Las principales decisiones fueron: reemplazar los valores -1 por la media o moda
según el tipo de variable, descartar `Competitors` por tener 74% de faltantes,
construir `avg_salary` desde el texto de `Salary Estimate`, y crear variables
derivadas de skills y seniority a partir del texto de las descripciones.
Todas estas transformaciones buscan maximizar la información disponible
para predecir el salario estimado de una oferta de Data Science.

# Sección 3 — Modelado

En esta sección se aplican las técnicas trabajadas en los Trabajos Prácticos N°2
(Regresión Lineal) y N°3 (Clasificación y Clustering) sobre el dataset de ofertas
laborales de Data Science (Glassdoor), continuando el trabajo de preparación de
datos realizado en la Sección 2.

Se desarrollan cuatro modelos:
- **3.1 — Planteo del problema**: definición de variables Y, X y término de error.
- **3.2 — Regresión**: predicción del salario promedio (`avg_salary`).
- **3.3 — Clasificación**: predicción de una categoría de salario (baja/media/alta).
- **3.4 — Clustering**: agrupamiento de ofertas laborales por perfil (K-Means).
- **3.5 — Conclusiones generales del TPI**.

## 3.1 — Planteo del problema

**Contexto:** una consultora de recursos humanos quiere analizar si el salario
estimado de una oferta de Data Science puede explicarse, al menos parcialmente,
a partir de las características de la empresa y del puesto.

| Elemento | Respuesta | Justificación |
|---|---|---|
| **Variable Y** | `avg_salary` (salario promedio estimado, en miles de USD) | Es la variable que la consultora quiere explicar/predecir; se construyó a partir del texto de `Salary Estimate`. |
| **Variables X** | `Rating`, `size_encoded`, habilidades técnicas (`python_yn`, `spark_yn`, `aws_yn`, `excel_yn`), `seniority`, `Type of ownership`, `Industry`, `Sector` | Aportan información sobre la empresa (tamaño, reputación, rubro) y el puesto (skills requeridas, nivel de seniority), todos factores que típicamente influyen en el salario ofrecido. |
| **Error ε** | (1) Negociación individual del candidato, no observable en el dataset. (2) Ubicación geográfica exacta y costo de vida de la ciudad, que el dataset captura solo parcialmente. | Son factores reales del mercado laboral que no están disponibles como columnas, por lo que el modelo nunca podrá explicar el 100% de la variabilidad del salario. |

### Predicción vs. inferencia

| Pregunta | Tipo de problema | Justificación |
|---|---|---|
| ¿Cuál sería el salario esperado de una oferta con Rating 4.0 en una empresa grande? | **Predicción** | Se busca un valor puntual estimado, no entender el mecanismo causal. |
| ¿El Rating de la empresa influye en el salario ofrecido? | **Inferencia** | Se busca entender si existe una relación y su dirección, no predecir un caso puntual. |
| ¿Qué sectores ofrecen los salarios promedio más altos? | **Análisis descriptivo** | Es una comparación directa entre grupos existentes en los datos, sin modelo predictivo de por medio. |
| ¿Cuánto aumenta el salario estimado al pasar de junior a senior? | **Inferencia** | Interesa el efecto (magnitud y dirección) de una variable sobre otra. |
| ¿Una oferta nueva, con ciertas características, a qué categoría de salario pertenece? | **Predicción** | Se clasifica un caso nuevo, no observado, en una categoría.

## 3.2 — Modelo de Regresión: predicción del salario

### 3.2.1 — Regresión Lineal
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


modelo_lineal = LinearRegression()
modelo_lineal.fit(X_train, y_train)

y_pred_lineal = modelo_lineal.predict(X_test)

print("Intercepto (β0):", round(modelo_lineal.intercept_, 2))
print("Cantidad de coeficientes (β):", len(modelo_lineal.coef_))

"""**Interpretación del intercepto:** representa el salario promedio estimado (en
miles de USD) cuando todas las variables predictoras valen cero — un valor de
referencia matemático, sin una interpretación práctica directa dado que ninguna
oferta real tiene todas sus variables en cero simultáneamente.

Veamos los coeficientes más relevantes para entender qué variables más influyen
en el salario estimado:
"""

coeficientes = pd.Series(modelo_lineal.coef_, index=X_train.columns).sort_values()

print("5 variables que MÁS reducen el salario estimado:")
print(coeficientes.head(5).round(2))

print("\n5 variables que MÁS aumentan el salario estimado:")
print(coeficientes.tail(5).round(2))

"""**Interpretación en lenguaje natural:** cada coeficiente indica cuánto cambia
`avg_salary` (en miles de USD) cuando esa variable aumenta en una unidad,
manteniendo el resto constante. Por ejemplo, si `python_yn` tiene un coeficiente
positivo, significa que las ofertas que mencionan Python en la descripción
tienden a pagar, en promedio, esa cantidad de miles de USD más que las que no
lo mencionan, controlando por el resto de las variables.

### 3.2.2 — Evaluación del modelo: residuos y métricas
"""

residuos = y_test.values[:5] - y_pred_lineal[:5]

print("Residuos de los primeros 5 registros de prueba (real - predicho):")
for real, pred, res in zip(y_test.values[:5], y_pred_lineal[:5], residuos):
    print(f"  Real: {real:6.1f}  |  Predicho: {pred:6.1f}  |  Residuo: {res:6.1f}")

mae = mean_absolute_error(y_test, y_pred_lineal)
mse = mean_squared_error(y_test, y_pred_lineal)
rmse = mse ** 0.5
r2 = r2_score(y_test, y_pred_lineal)

print(f"MAE  (Error Absoluto Medio):     {mae:.2f}")
print(f"MSE  (Error Cuadrático Medio):   {mse:.2f}")
print(f"RMSE (Raíz del Error Cuadrático): {rmse:.2f}")
print(f"R²   (Coeficiente de determinación): {r2:.3f}")
print(f"\nRango de salarios en el dataset: {y.min():.0f} a {y.max():.0f} (mil USD)")

"""**¿El error es grande o pequeño?** El RMSE obtenido representa una fracción del
rango total de salarios del dataset (que va de un mínimo a un máximo de varias
decenas de miles de USD). Un RMSE de esa magnitud indica un error moderado: el
modelo captura una tendencia general, pero todavía deja sin explicar una parte
considerable de la variabilidad del salario, lo cual es razonable dado que
muchas de las variables más influyentes en el mercado real (negociación,
ubicación específica) no están en el dataset.

**Gráfico de residuos vs. valores predichos** (bonus):
"""

fig, ax = plt.subplots()
ax.scatter(y_pred_lineal, y_test.values - y_pred_lineal, alpha=0.5, color='steelblue')
ax.axhline(y=0, color='red', linestyle='--')
ax.set_xlabel('Valor predicho (avg_salary)')
ax.set_ylabel('Residuo (real - predicho)')
ax.set_title('Residuos vs. valores predichos — Regresión Lineal')
plt.show()

"""**Gráfico 5 — Residuos:** si los puntos se distribuyen de forma aproximadamente
aleatoria alrededor de la línea de cero, sin un patrón claro (forma de embudo,
curva, etc.), el modelo lineal es una elección razonable. Si se observa un
patrón sistemático, sería indicio de que la relación no es puramente lineal.

### 3.2.3 — Comparación con Random Forest

Como comparación, se entrena también un modelo de **Random Forest Regressor**
(ensamble de árboles de decisión), que permite capturar relaciones no lineales
entre las variables y el salario.
"""

from sklearn.ensemble import RandomForestRegressor

rf_regresor = RandomForestRegressor(n_estimators=100, random_state=42)
rf_regresor.fit(X_train, y_train)

y_pred_rf = rf_regresor.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = mean_squared_error(y_test, y_pred_rf) ** 0.5
r2_rf = r2_score(y_test, y_pred_rf)

print("Comparación de modelos de regresión:")
print(f"{'Modelo':<20}{'MAE':>10}{'RMSE':>10}{'R²':>10}")
print(f"{'Regresión Lineal':<20}{mae:>10.2f}{rmse:>10.2f}{r2:>10.3f}")
print(f"{'Random Forest':<20}{mae_rf:>10.2f}{rmse_rf:>10.2f}{r2_rf:>10.3f}")

importancias = pd.Series(rf_regresor.feature_importances_, index=X_train.columns)
importancias = importancias.sort_values(ascending=False).head(10)

fig, ax = plt.subplots()
importancias.sort_values().plot(kind='barh', ax=ax, color='seagreen')
ax.set_xlabel('Importancia')
ax.set_title('Top 10 variables más importantes — Random Forest')
plt.tight_layout()
plt.show()

"""**Gráfico 6 — Importancia de variables:** muestra qué variables aporta más el
Random Forest a la hora de predecir el salario, a diferencia de los coeficientes
de la regresión lineal, que indican dirección y magnitud pero no necesariamente
capacidad predictiva global.

### 3.2.4 — Reflexión final sobre el modelo de regresión

¿El modelo lineal simple es suficiente? Es un buen punto de partida porque es
interpretable: permite explicar en lenguaje natural cómo cada variable afecta
al salario. Sin embargo, el Random Forest generalmente captura mejor las
relaciones no lineales (por ejemplo, combinaciones de sector + seniority), por
lo que conviene usarlo quitando "fricción" cuando la prioridad es predecir con
precisión más que interpretar.

¿Qué variable agregaría? Información sobre la ubicación geográfica desagregada
(ciudad/estado, no solo región) probablemente mejoraría el modelo, ya que el
costo de vida y la demanda local de talento varían fuertemente por zona.

¿El objetivo es predicción o inferencia? ambos: se busca
predecir el salario de una oferta nueva (predicción), pero también entender qué
factores lo explican para asesorar a una empresa o candidato (inferencia).

¿Qué haría si el RMSE fuese muy alto? Revisaría primero la calidad de los datos
(más variables relevantes, mejor tratamiento de outliers), y si el problema
persiste, probaría modelos más flexibles (Random Forest, Gradient Boosting) o
aceptaría que el problema tiene un componente de error irreducible alto.

## 3.3 — Modelo de Clasificación: categoría de salario

Siguiendo la misma lógica que el TP3, se crea una **etiqueta artificial** —
`categoria_salario` — dividiendo `avg_salary` en tres grupos por cuantiles, y se
entrena un modelo de clasificación para predecirla a partir del resto de las
variables (sin usar `avg_salary` como predictora, ya que sería la variable
usada para construir la etiqueta).
"""

df_clasif = df_model.copy()

df_clasif['categoria_salario'] = pd.qcut(
    df_clasif['avg_salary'],
    q=3,
    labels=['baja', 'media', 'alta']
)

print("Distribución de categorías de salario:")
print(df_clasif['categoria_salario'].value_counts())

"""**¿Qué criterio se usó?** Se dividió `avg_salary` en tercios usando cuantiles,
de forma que cada categoría contenga aproximadamente la misma cantidad de
ofertas. **¿Es una verdad real o una regla creada para el ejercicio?** Es una
regla creada para el ejercicio: no existe un corte "oficial" entre salario bajo,
medio y alto, simplemente se utiliza la distribución del propio dataset.
**¿Por qué corresponde a aprendizaje supervisado?** Porque la variable objetivo
(`categoria_salario`) es conocida para cada registro de entrenamiento, y el
modelo aprende a partir de esos ejemplos etiquetados.
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X_clasif = df_clasif.drop(columns=['avg_salary', 'categoria_salario'])
y_clasif = df_clasif['categoria_salario']

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X_clasif, y_clasif,
    test_size=0.3,
    random_state=42,
    stratify=y_clasif
)

clasificador = RandomForestClassifier(n_estimators=100, random_state=42)
clasificador.fit(X_train_c, y_train_c)

y_pred_c = clasificador.predict(X_test_c)

print("Accuracy:", round(accuracy_score(y_test_c, y_pred_c), 3))
print()
print(classification_report(y_test_c, y_pred_c))

matriz = confusion_matrix(y_test_c, y_pred_c, labels=['baja', 'media', 'alta'])

fig, ax = plt.subplots()
sns.heatmap(matriz, annot=True, fmt='d', cmap='Blues',
            xticklabels=['baja', 'media', 'alta'],
            yticklabels=['baja', 'media', 'alta'], ax=ax)
ax.set_xlabel('Predicho')
ax.set_ylabel('Real')
ax.set_title('Matriz de confusión — Clasificación de salario')
plt.show()

"""**Gráfico 7 — Matriz de confusión.**

¿Qué tan bien predijo el modelo las categorías? El accuracy obtenido indica la
proporción de ofertas correctamente clasificadas sobre el total de prueba.

¿Qué significa el accuracy? Es la proporción de predicciones correctas sobre el
total de casos evaluados; un accuracy cercano a 1 indica que casi todas las
ofertas fueron clasificadas en la categoría correcta.

¿Qué muestra la matriz de confusión? La diagonal principal son los aciertos por
categoría; fuera de la diagonal se ven los errores, típicamente concentrados
entre categorías vecinas (por ejemplo, confundir "media" con "alta" es más
frecuente que confundir "baja" con "alta", porque son grupos contiguos en la
distribución de salarios).

¿Por qué este modelo sí es supervisado? Porque se entrenó usando ejemplos con
la etiqueta `categoria_salario` ya conocida, a diferencia del clustering de la
siguiente sección, donde no se usa ninguna etiqueta.

## 3.4 — Clustering: perfiles de ofertas laborales (K-Means)

Se aplica K-Means sobre el dataset `df_no_supervisado` preparado en la Sección
2.5, **sin usar `categoria_salario`** ni ninguna otra etiqueta, ya que el
objetivo es que el algoritmo descubra agrupamientos por sí mismo a partir de
las características numéricas.
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_cluster_scaled = scaler.fit_transform(df_no_supervisado)

print(f"Variables utilizadas para clustering: {list(df_no_supervisado.columns)}")
print(f"Dimensiones escaladas: {X_cluster_scaled.shape}")

"""**¿Por qué es necesario escalar los datos?** Hay que escalar porque K-Means agrupa según distancias. Si dejamos avg_salary tal cual (números tipo 80, 120) al lado de columnas binarias como Sector_Retail (0 o 1), el salario va a pesar mucho más solo por tener números más grandes, aunque no sea realmente más importante. Escalando, todas las variables quedan en igualdad de condiciones.

### 3.4.1 — Método del codo
"""

from sklearn.cluster import KMeans

inercias = []
rango_k = range(2, 9)

for k in rango_k:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_cluster_scaled)
    inercias.append(kmeans.inertia_)

fig, ax = plt.subplots()
ax.plot(list(rango_k), inercias, marker='o', color='steelblue')
ax.set_xlabel('Cantidad de clusters (K)')
ax.set_ylabel('Inercia')
ax.set_title('Método del codo — Ofertas laborales')
plt.show()

"""**Gráfico 8 — Método del codo.** La inercia mide la suma de las distancias al
cuadrado entre cada punto y el centroide de su cluster; cuanto más bajo, más
compactos son los grupos, pero siempre baja al aumentar K. El "codo" (punto
donde la curva deja de bajar fuertemente) sugiere un valor de K razonable: a
partir de ahí, agregar más clusters ya no mejora demasiado la compacidad, pero
sí complica la interpretación. No conviene elegir el K más grande posible
porque, llevado al extremo, cada punto terminaría siendo su propio cluster,
perdiendo todo valor explicativo.

### 3.4.2 — Aplicación de K-Means y métricas
"""

k_elegido = 3

kmeans_final = KMeans(n_clusters=k_elegido, random_state=42, n_init=10)
df_no_supervisado_clusters = df_no_supervisado.copy()
df_no_supervisado_clusters['cluster'] = kmeans_final.fit_predict(X_cluster_scaled)

print("Cantidad de ofertas por cluster:")
print(df_no_supervisado_clusters['cluster'].value_counts().sort_index())

from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

labels = df_no_supervisado_clusters['cluster']

silhouette = silhouette_score(X_cluster_scaled, labels)
davies = davies_bouldin_score(X_cluster_scaled, labels)
calinski = calinski_harabasz_score(X_cluster_scaled, labels)

print(f"Silhouette Score:        {silhouette:.3f}")
print(f"Davies-Bouldin Index:    {davies:.3f}")
print(f"Calinski-Harabasz Index: {calinski:.1f}")

"""¿El Silhouette Score indica grupos bien separados o mezclados? Un valor cercano
a 1 indica clusters bien separados y compactos; un valor cercano a 0 indica
clusters que se superponen entre sí; valores negativos indicarían puntos mal
asignados. El valor obtenido debe leerse en esa escala.

¿Qué significa que Davies-Bouldin sea bajo? Cuanto más bajo, mejor: indica que
los clusters están bien separados entre sí en relación con su propia dispersión
interna.

¿Por qué estas métricas no alcanzan por sí solas? Son medidas puramente
geométricas (qué tan compactos y separados están los puntos), pero no dicen si
los grupos resultantes tienen sentido de negocio. Por eso, además de las
métricas, conviene interpretar el contenido de cada cluster, como se hace a
continuación.

### 3.4.3 — Interpretación de los clusters
"""

perfil_clusters = df_no_supervisado_clusters.groupby('cluster').mean(numeric_only=True).round(2)
print("Perfil promedio de cada cluster:")
perfil_clusters

from sklearn.decomposition import PCA

pca = PCA(n_components=2, random_state=42)
componentes = pca.fit_transform(X_cluster_scaled)

fig, ax = plt.subplots()
scatter = ax.scatter(componentes[:, 0], componentes[:, 1],
                      c=df_no_supervisado_clusters['cluster'], cmap='viridis', alpha=0.6)
ax.set_xlabel('Componente principal 1')
ax.set_ylabel('Componente principal 2')
ax.set_title('Clusters de ofertas laborales (proyección PCA 2D)')
legend = ax.legend(*scatter.legend_elements(), title="Cluster")
ax.add_artist(legend)
plt.show()

"""**Gráfico 9 — Visualización de clusters (PCA 2D).** Dado que se usaron varias
variables para el clustering, se proyectan los datos a 2 dimensiones mediante
PCA solo para poder visualizarlos; el agrupamiento real se hizo en el espacio
completo de variables escaladas.

A partir de la tabla de medias por cluster, se pueden caracterizar los perfiles
de ofertas laborales: por ejemplo, un cluster puede agrupar ofertas de salario
y rating altos en empresas grandes, otro ofertas de salario más bajo en
empresas chicas, y un tercero un perfil intermedio — la lectura específica debe
hacerse sobre los valores reales obtenidos en `perfil_clusters`.

## 3.5 — Conclusiones generales del TPI

A lo largo de este trabajo se aplicaron las tres técnicas centrales de la
materia sobre el dataset de ofertas de Data Science en Glassdoor:

- **Regresión:** tanto la Regresión Lineal como el Random Forest lograron
  capturar una relación entre las características de la oferta/empresa y el
  salario estimado, aunque con un error que indica que una parte relevante del
  salario depende de factores no incluidos en el dataset (negociación,
  ubicación específica, etc.).
- **Clasificación:** el modelo de Random Forest sobre la etiqueta artificial
  `categoria_salario` permitió evaluar qué tan bien se puede distinguir entre
  ofertas de salario bajo, medio y alto a partir de las características
  disponibles, con el accuracy y la matriz de confusión como evidencia.
- **Clustering:** K-Means permitió descubrir, sin usar ninguna etiqueta,
  agrupamientos naturales de ofertas laborales según salario, rating y otras
  variables, confirmando (o matizando) las categorías que se habían definido
  manualmente para la clasificación.

En conjunto, el análisis muestra que el salario de una oferta de Data Science
puede explicarse parcialmente a partir de variables observables de la empresa
y del puesto, pero que existe un margen de error razonable y esperable dado que
el mercado laboral real depende también de factores que no están presentes en
este dataset.

## Exportar datos para Power BI
"""

# Exporto las columnas necesarias para armar el dashboard en Power BI


df_powerbi = df_clean.dropna(subset=['avg_salary']).reset_index(drop=True).copy()

cols_powerbi = [
    'Job Title', 'avg_salary', 'Rating', 'Company Name', 'Location',
    'Size', 'Type of ownership', 'Industry', 'Sector', 'seniority',
    'python_yn', 'spark_yn', 'aws_yn', 'excel_yn'
]
df_powerbi = df_powerbi[[c for c in cols_powerbi if c in df_powerbi.columns]]

df_powerbi['Company Name'] = df_powerbi['Company Name'].str.split('\n').str[0]

# categoria de salario (baja/media/alta) calculada
df_powerbi['categoria_salario'] = df_clasif['categoria_salario'].values

# cluster asignado
df_powerbi['cluster'] = df_no_supervisado_clusters['cluster'].values

df_powerbi.to_csv('datos_dashboard.csv', index=False)
print(f"CSV exportado: {df_powerbi.shape[0]} filas, {df_powerbi.shape[1]} columnas")
df_powerbi.head()